# Generated by Django 5.1 on 2024-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ans_a', models.CharField(max_length=1000)),
                ('Ans_b', models.CharField(max_length=1000)),
                ('Ans_c', models.CharField(max_length=1000)),
                ('Ans_d', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('q_id', models.IntegerField()),
            ],
        ),
    ]
