# Generated by Django 5.1 on 2024-10-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_answers_4_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.answers_4'),
        ),
        migrations.AddField(
            model_name='question',
            name='ans_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answers_4',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.IntegerField(null=True),
        ),
    ]
