# Generated by Django 5.1 on 2024-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_question_answers_question_ans_id_alter_answers_4_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans_id',
        ),
        migrations.AddField(
            model_name='question',
            name='Ans_a',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='Ans_b',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='Ans_c',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='Ans_d',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='Corect_ans',
            field=models.CharField(blank=True, choices=[('A', models.TextField(blank=True, max_length=1000)), ('B', models.TextField(blank=True, max_length=1000)), ('C', models.TextField(blank=True, max_length=1000)), ('D', models.TextField(blank=True, max_length=1000))], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Answers_4',
        ),
    ]
