# Generated by Django 5.1 on 2024-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_question_answers_remove_question_ans_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Corect_ans',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.IntegerField(default=1),
        ),
    ]
