# Generated by Django 5.1 on 2024-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_question_corect_ans_alter_question_q_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_id',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='Corect_ans',
            field=models.CharField(blank=True, choices=[(models.TextField(blank=True, max_length=1000), 'A'), (models.TextField(blank=True, max_length=1000), 'B'), (models.TextField(blank=True, max_length=1000), 'C'), (models.TextField(blank=True, max_length=1000), 'D')], max_length=1),
        ),
    ]
