# Generated by Django 5.1.2 on 2024-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_question_q_id_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000)),
                ('Ans_a', models.TextField(blank=True, max_length=1000)),
                ('Ans_b', models.TextField(blank=True, max_length=1000)),
                ('Ans_c', models.TextField(blank=True, max_length=1000)),
                ('Ans_d', models.TextField(blank=True, max_length=1000)),
                ('Corect_ans_a', models.CharField(choices=[('True', 'đúng'), ('False', 'Sai')], default=None, max_length=5)),
                ('Corect_ans_b', models.CharField(choices=[('True', 'đúng'), ('False', 'Sai')], default=None, max_length=5)),
                ('Corect_ans_c', models.CharField(choices=[('True', 'đúng'), ('False', 'Sai')], default=None, max_length=5)),
                ('Corect_ans_d', models.CharField(choices=[('True', 'đúng'), ('False', 'Sai')], default=None, max_length=5)),
                ('type', models.IntegerField(default=2, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='Corect_ans',
            field=models.CharField(choices=[('A', 'Answer A'), ('B', 'Answer B'), ('C', 'Answer C'), ('D', 'Answer D')], default=None, max_length=1),
        ),
    ]
