# Generated by Django 5.1.2 on 2024-10-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question2_alter_question_corect_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='lop_hoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bai_hoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('noi_dung', models.TextField()),
                ('file_di_kem', models.FileField(blank=True, upload_to='')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lop_hoc')),
            ],
        ),
    ]
