# Generated by Django 5.1.3 on 2024-11-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_uploadedfile_remove_bai_hoc_lop_delete_lop_hoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bai_hoc'),
        ),
    ]
