# Generated by Django 5.1.3 on 2024-12-13 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_workspace_remove_block_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='description',
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='base.workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='My Workspace', max_length=100),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
