# Generated by Django 5.1.3 on 2024-12-13 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_block_page_remove_workspace_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('image', 'Image'), ('todolist', 'ToDoList')], max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='base.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='My Personal Space', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
