# Generated by Django 5.1.3 on 2025-01-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_cau_hoi1_cau_hoi2_remove_workspace_user_and_more'),
        ('base', '0020_remove_userprofile_user_avata_and_more'),
    ]

    operations = [
    ]
