# Generated by Django 5.1.3 on 2024-12-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_userprofile_comment_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
