# Generated by Django 5.1.3 on 2025-01-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_delete_cau_hoi1_delete_cau_hoi2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
