# Generated by Django 5.1.3 on 2025-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_useractivity_ip_address_useractivity_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2',
            name='De',
            field=models.CharField(blank=True, choices=[('1', 'Đề 1'), ('2', 'Đề 2'), ('3', 'Đề 3'), ('4', 'Đề 4'), ('5', 'Đề 5'), ('6', 'Đề 6')], max_length=100, null=True, verbose_name='Đề'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='Loai',
            field=models.CharField(choices=[('cau_hoi_loai_1', 'cau_hoi_loai_1'), ('chung', 'Chung'), ('ICT', 'ICT'), ('CS', 'CS')], default='chung', max_length=100, verbose_name='Loại câu hỏi'),
        ),
    ]
