# Generated by Django 5.1.3 on 2025-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_question2_de_alter_question2_loai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2',
            name='Corect_ans_a',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('True', 'Đúng'), ('False', 'Sai')], default='False', max_length=5, verbose_name='Đáp án A đúng?'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='Corect_ans_b',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('True', 'Đúng'), ('False', 'Sai')], default='False', max_length=5, verbose_name='Đáp án B đúng?'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='Corect_ans_c',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('True', 'Đúng'), ('False', 'Sai')], default='False', max_length=5, verbose_name='Đáp án C đúng?'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='Corect_ans_d',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('True', 'Đúng'), ('False', 'Sai')], default='False', max_length=5, verbose_name='Đáp án D đúng?'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='Loai',
            field=models.CharField(choices=[('None', 'None'), ('chung', 'Chung'), ('ICT', 'ICT'), ('CS', 'CS')], default='None', max_length=100, verbose_name='Loại câu hỏi'),
        ),
    ]
