# Generated by Django 5.1.3 on 2025-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_question2_corect_ans_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2',
            name='A',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Đáp án A'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='B',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Đáp án B'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='C',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Đáp án C'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='D',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Đáp án D'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='type',
            field=models.IntegerField(choices=[('1', 'Đề 1'), ('2', 'Đề 2'), ('3', 'Đề 3'), ('4', 'Đề 4'), ('5', 'Đề 5'), ('6', 'Đề 6')], default=1, verbose_name='Loại câu hỏi'),
        ),
    ]
